name: AkroFolis
authors: [ZetaStormy, Thelion102009]
version: ${version}
description: A modern Minecraft server hub core solution. Based on DeluxeHub by ItsLewizzz. Fully compatible with Paper & Folia 1.21.x
api-version: "1.21"
folia-supported: true
main: me.zetastormy.akropolis.AkropolisPlugin
loader: me.zetastormy.akropolis.AkropolisPluginLoader

dependencies:
  server:
    Essentials:
      load: AFTER
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    HeadDatabase:
      load: BEFORE
      required: false
    Multiverse-Core:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    NoteBlockAPI:
      load: BEFORE
      required: false

permissions:
  akrofolis.*:
    description: Gives access to all Akrofolis permissions
    children:
      akrofolis.command.*: true
      akrofolis.bypass.*: true
      akrofolis.alert.*: true
      akrofolis.item.*: true
      akrofolis.player.*: true
      akrofolis.block.*: true
  akrofolis.command.*:
    description: Gives access to all command permissions
    children:
      akrofolis.command.help: true
      akrofolis.command.reload: true
      akrofolis.command.scoreboard: true
      akrofolis.command.openmenu: true
      akrofolis.command.holograms: true
      akrofolis.command.gamemode: true
      akrofolis.command.gamemode.others: true
      akrofolis.command.clearchat: true
      akrofolis.command.lockchat: true
      akrofolis.command.fly: true
      akrofolis.command.fly.others: true
      akrofolis.command.setlobby: true
      akrofolis.command.vanish: true
      akrofolis.command.songplayer: true
  akrofolis.bypass.*:
    description: Gives access to all bypass permissions
    children:
      akrofolis.bypass.antiswear: true
      akrofolis.bypass.commands: true
      akrofolis.bypass.lockchat: true
      akrofolis.bypass.antiwdl: true
      akrofolis.bypass.doublejump: false
  akrofolis.alert.*:
    description: Gives access to all alert permissions
    children:
      akrofolis.alert.antiswear: true
      akrofolis.alert.antiwdl: true
  akrofolis.item.*:
    description: Gives access to all item based permissions
    children:
      akrofolis.item.drop: true
      akrofolis.item.pickup: true
  akrofolis.player.*:
    description: Gives access to all player based permissions
    children:
      akrofolis.player.pvp: true
  akrofolis.block.*:
    description: Gives access to all block based permissions
    children:
      akrofolis.block.break: true
      akrofolis.block.place: true
      akrofolis.block.interact: true
  akrofolis.chat.group.*:
    description: Determines which chat format and cooldown time should be used
    children:
      akrofolis.chat.group.default: true
